name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@44.210.136.208 'echo "SSH connection successful"'
        
    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 ubuntu@44.210.136.208 << 'EOF'
        cd /home/ubuntu/app
        git pull origin main
        docker-compose down
        docker-compose up --build -d
        EOF